#!/bin/bash
trap 'abort' 0

set -euo pipefail

abort()
{

  echo "An error occurred in the plugin. Exiting..." >&2
  exit 1
}

echo "--- Sending deployment events to datadog"

PAYLOAD="{ \"title\": \"${BUILDKITE_PLUGIN_DATADOG_EVENT_TITLE}\", \"priority\": \"${BUILDKITE_PLUGIN_DATADOG_EVENT_PRIORITY-normal}\", \"tags\": \"${BUILDKITE_PLUGIN_DATADOG_EVENT_TAGS}\", \"alert_type\": \"${BUILDKITE_PLUGIN_DATADOG_EVENT_ALERT_TYPE-info}\" }"
API_END_POINT="https://app.datadoghq.com/api/v1/events?api_key=${!BUILDKITE_PLUGIN_DATADOG_EVENT_ENV}"

echo "Event payload: $PAYLOAD"

curl -X POST -H "Content-type: application/json" -d "$PAYLOAD" "$API_END_POINT" 2>&1 | grep 'status":"ok"'

if [[ $? != 0 ]]; then
  abort
fi

trap : 0
